apiVersion: apps/v1
kind: Deployment 
metadata:
  name: hola-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.20-alpine
        ports: 
        - containerPort: 80
